### ISSUE TITLE
msgfmt aborts on long strings in non-Latin alphabets

### ISSUE THREAD

**Issue by awilfox** [sabotage-linux/gettext-tiny#28]
Seen in [the Dzongkha translation of GConf 3.2.6](https://github.com/GNOME/gconf/blob/master/po/dz.po#L1170-L1173):

```
/bin/sh: line 1: 25453 Aborted                 /usr/bin/msgfmt -o $file dz.po
```

Further inspection:

```
(gdb) bt
#0  0x00003ffff7f9f768 in __syscall4 (d=8, c=0, b=70368744151424, a=2, n=174) at ./arch/powerpc64/syscall_arch.h:54
#1  __restore_sigs (set=0x3fffffff9980) at src/signal/block.c:43
#2  0x00003ffff7f9fa6c in raise (sig=<optimized out>) at src/signal/raise.c:13
#3  0x00003ffff7f6b8c4 in abort () at src/exit/abort.c:13
#4  0x0000000100004dfc in get_length_and_convert (info=0x3fffffff9d38, 
    x=0x3fffffff9e80 "རིམ་སྒྲག་སར་བར་ལུ་ འབྲི་བཏུབ་པའི་གནད་སྡུད་གཞི་རྟེན་མེདཔ་ལས་ ལྡེ་མིག"..., 
    end=0x3fffffffae78 "Unable to store a value at key '%s', as the configuration server has no writable databases. There are some common causes of this problem: 1) your configuration path file %s/path doesn't contain any da"..., 
    convbuf=0x3fffffffae78 "Unable to store a value at key '%s', as the configuration server has no writable databases. There are some common causes of this problem: 1) your configuration path file %s/path doesn't contain any da"..., convbuflen=16384)
    at src/poparser.c:75
#5  0x0000000100005438 in poparser_feed_line (p=0x3fffffff9d38, 
    line=0x3fffffff9e78 "msgstr \"རིམ་སྒྲག་སར་བར་ལུ་ འབྲི་བཏུབ་པའི་གནད་སྡུད་གཞི་རྟེན་མེདཔ་ལས་ ལྡེ", <incomplete sequence \340>..., buflen=4096)
    at src/poparser.c:198
#6  0x0000000100003340 in process (in=0x100020080, out=0x3ffff7ffc020) at src/msgfmt.c:443
#7  0x00000001000045b4 in main (argc=4, argv=0x3ffffffff028) at src/msgfmt.c:608
```

Going to frame 4, `get_length_and_convert`, we can see `e` is wrong:

```
(gdb) x/s e
0x3fffffffae76: <incomplete sequence \340>
(gdb) x/x e
0x3fffffffae76: 0xe0
```

Going up to frame 6, `process`, we can see that the reason is because the string was cut off in the middle:

```
(gdb) p sizeof(line)
$5 = 4096
(gdb) p lp
$7 = 0x3fffffff9e78 "msgstr \"རིམ་སྒྲག་སར་བར་ལུ་ འབྲི་བཏུབ་པའི་གནད་སྡུད་གཞི་རྟེན་མེདཔ་ལས་ ལྡེ", <incomplete sequence \340>...
(gdb) p lp+4092
$11 = 0x3fffffffae74 "\275\233", <incomplete sequence \340>
```

This is what we expect to see having a short read of the line; BD 9B E0 are the 4,093rd, 4,094th, and 4,095th bytes.  The line in question is 4,279 bytes long.

A quick-and-dirty solution was to bump `line` to be an array 8,192 bytes long, and `convbuf` equally raised to 32,768 bytes long.  I am not sure how much of the stack is used in other modules, so I am unsure if this limit is safe to use or not.

**Comment by rofl0r** [comment]
those values are perfectly fine. would you mind opening a PR with your changes ? thanks!

**Comment by awilfox** [comment]
Sent in PR #29.
